### ISSUE TITLE
cflags in makefile

### ISSUE THREAD

**Issue by ghost** [samuelventura/baud#3]
Baud does not build on opensuse LEAP 42.2 JEOS running on Raspberry pi 3.
I do not have exact logs  but compiler kept complaining about C99 and some GNU flag and eventually build fails.

It builds and run fine with the following changes in the Makefile: 

CFLAGS += -std=c99 -D_GNU_SOURCE

$(TARGET): src/*
	mkdir -p priv/native
	gcc  $(CFLAGS) -o $(TARGET) $(SOURCES)

Hope this help.

**Comment by samuelventura** [comment]
Thanks for the head ups. Will try that once I get one Raspberry pi 3.

**Comment by ghost** [comment]
I can now confirm that version 0.5.0 compiles properly on RPI 3 except I have to compile twice, so this issue can be closed . 

Thanks for this lib . just for information I have used your lib to communicate to my utility meter via RPI 3 board and then send it to web server /cloud for storage.
